import os

MONGODB_PORT = os.getenv('MONGODB_PORT')
MONGODB_NAME = os.getenv('MONGODB_NAME')
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
GOOGLE_AI_API_KEY = os.getenv('GOOGLE_AI_API_KEY')
ALLOWED_TELEGRAM_USERNAMES = os.getenv('ALLOWED_TELEGRAM_USERNAMES')
DEFAULT_CHAT_HISTORY_LIMIT = os.getenv('DEFAULT_CHAT_HISTORY_LIMIT')
DEVELOPER_CHAT_ID = os.getenv('DEVELOPER_CHAT_ID')